// Code generated by protoc-gen-go.
// source: msg/transfer.proto
// DO NOT EDIT!

/*
Package transfer is a generated protocol buffer package.

It is generated from these files:
	msg/transfer.proto

It has these top-level messages:
	Transfer
	SendInit
	SendPartial
	SendFinish
	RecvInit
	RecvPartial
	RecvFinish
*/
package transfer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Transfer struct {
	SnedInit         *SendInit      `protobuf:"bytes,1,opt,name=sned_init" json:"sned_init,omitempty"`
	SendPartial      *SendPartial   `protobuf:"bytes,2,opt,name=send_partial" json:"send_partial,omitempty"`
	SendFinish       *SendFinish    `protobuf:"bytes,3,opt,name=send_finish" json:"send_finish,omitempty"`
	RecvInit         *RecvInit      `protobuf:"bytes,4,opt,name=recv_init" json:"recv_init,omitempty"`
	RecvPartial      *RecvPartial   `protobuf:"bytes,5,opt,name=recv_partial" json:"recv_partial,omitempty"`
	RecvStatus       []*SendPartial `protobuf:"bytes,6,rep,name=recv_status" json:"recv_status,omitempty"`
	RecvFinish       *RecvFinish    `protobuf:"bytes,7,opt,name=recv_finish" json:"recv_finish,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Transfer) Reset()                    { *m = Transfer{} }
func (m *Transfer) String() string            { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()               {}
func (*Transfer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Transfer) GetSnedInit() *SendInit {
	if m != nil {
		return m.SnedInit
	}
	return nil
}

func (m *Transfer) GetSendPartial() *SendPartial {
	if m != nil {
		return m.SendPartial
	}
	return nil
}

func (m *Transfer) GetSendFinish() *SendFinish {
	if m != nil {
		return m.SendFinish
	}
	return nil
}

func (m *Transfer) GetRecvInit() *RecvInit {
	if m != nil {
		return m.RecvInit
	}
	return nil
}

func (m *Transfer) GetRecvPartial() *RecvPartial {
	if m != nil {
		return m.RecvPartial
	}
	return nil
}

func (m *Transfer) GetRecvStatus() []*SendPartial {
	if m != nil {
		return m.RecvStatus
	}
	return nil
}

func (m *Transfer) GetRecvFinish() *RecvFinish {
	if m != nil {
		return m.RecvFinish
	}
	return nil
}

type SendInit struct {
	Total            *uint32 `protobuf:"varint,1,req,name=total" json:"total,omitempty"`
	Block            *uint32 `protobuf:"varint,2,req,name=block" json:"block,omitempty"`
	Cnt              *uint32 `protobuf:"varint,3,req,name=cnt" json:"cnt,omitempty"`
	Name             *string `protobuf:"bytes,4,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SendInit) Reset()                    { *m = SendInit{} }
func (m *SendInit) String() string            { return proto.CompactTextString(m) }
func (*SendInit) ProtoMessage()               {}
func (*SendInit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SendInit) GetTotal() uint32 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

func (m *SendInit) GetBlock() uint32 {
	if m != nil && m.Block != nil {
		return *m.Block
	}
	return 0
}

func (m *SendInit) GetCnt() uint32 {
	if m != nil && m.Cnt != nil {
		return *m.Cnt
	}
	return 0
}

func (m *SendInit) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type SendPartial struct {
	Sequence         *uint32 `protobuf:"varint,1,req,name=sequence" json:"sequence,omitempty"`
	Size             *uint32 `protobuf:"varint,2,req,name=size" json:"size,omitempty"`
	Checksum         []byte  `protobuf:"bytes,3,opt,name=checksum" json:"checksum,omitempty"`
	Start            *uint32 `protobuf:"varint,4,req,name=start" json:"start,omitempty"`
	End              *uint32 `protobuf:"varint,5,req,name=end" json:"end,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SendPartial) Reset()                    { *m = SendPartial{} }
func (m *SendPartial) String() string            { return proto.CompactTextString(m) }
func (*SendPartial) ProtoMessage()               {}
func (*SendPartial) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SendPartial) GetSequence() uint32 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return 0
}

func (m *SendPartial) GetSize() uint32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *SendPartial) GetChecksum() []byte {
	if m != nil {
		return m.Checksum
	}
	return nil
}

func (m *SendPartial) GetStart() uint32 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

func (m *SendPartial) GetEnd() uint32 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return 0
}

type SendFinish struct {
	Checksum         []byte `protobuf:"bytes,1,opt,name=checksum" json:"checksum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SendFinish) Reset()                    { *m = SendFinish{} }
func (m *SendFinish) String() string            { return proto.CompactTextString(m) }
func (*SendFinish) ProtoMessage()               {}
func (*SendFinish) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SendFinish) GetChecksum() []byte {
	if m != nil {
		return m.Checksum
	}
	return nil
}

type RecvInit struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RecvInit) Reset()                    { *m = RecvInit{} }
func (m *RecvInit) String() string            { return proto.CompactTextString(m) }
func (*RecvInit) ProtoMessage()               {}
func (*RecvInit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RecvInit) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type RecvPartial struct {
	Sequence         *uint32 `protobuf:"varint,1,req,name=sequence" json:"sequence,omitempty"`
	Status           *uint32 `protobuf:"varint,2,req,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RecvPartial) Reset()                    { *m = RecvPartial{} }
func (m *RecvPartial) String() string            { return proto.CompactTextString(m) }
func (*RecvPartial) ProtoMessage()               {}
func (*RecvPartial) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RecvPartial) GetSequence() uint32 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return 0
}

func (m *RecvPartial) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

type RecvFinish struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RecvFinish) Reset()                    { *m = RecvFinish{} }
func (m *RecvFinish) String() string            { return proto.CompactTextString(m) }
func (*RecvFinish) ProtoMessage()               {}
func (*RecvFinish) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*Transfer)(nil), "transfer.transfer")
	proto.RegisterType((*SendInit)(nil), "transfer.send_init")
	proto.RegisterType((*SendPartial)(nil), "transfer.send_partial")
	proto.RegisterType((*SendFinish)(nil), "transfer.send_finish")
	proto.RegisterType((*RecvInit)(nil), "transfer.recv_init")
	proto.RegisterType((*RecvPartial)(nil), "transfer.recv_partial")
	proto.RegisterType((*RecvFinish)(nil), "transfer.recv_finish")
}

var fileDescriptor0 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x91, 0xd1, 0x4e, 0x83, 0x30,
	0x14, 0x86, 0x33, 0xd8, 0xe6, 0x38, 0x80, 0x31, 0x35, 0x1a, 0xbc, 0x92, 0xf4, 0xc2, 0x10, 0x35,
	0xd3, 0xf8, 0x0c, 0x3e, 0x86, 0x89, 0xc1, 0xda, 0x39, 0xb2, 0x51, 0x66, 0x5b, 0xbc, 0xf0, 0xd5,
	0x7c, 0x39, 0x4f, 0x0f, 0x8c, 0x40, 0x63, 0xbc, 0xfc, 0xf3, 0xff, 0xe7, 0xf4, 0x3b, 0x7f, 0x81,
	0xd5, 0xe6, 0xe3, 0xc1, 0xea, 0x52, 0x99, 0x8d, 0xd4, 0xeb, 0x83, 0x6e, 0x6c, 0xc3, 0x56, 0x47,
	0xcd, 0x7f, 0x02, 0x18, 0x04, 0xbb, 0x81, 0xc8, 0x28, 0xf9, 0xfe, 0x5a, 0xa9, 0xca, 0x66, 0xb3,
	0x7c, 0x56, 0xc4, 0x4f, 0xe7, 0xeb, 0x61, 0xd4, 0x48, 0xd5, 0x59, 0xec, 0x1e, 0x12, 0x12, 0x87,
	0x52, 0xdb, 0xaa, 0xdc, 0x67, 0x01, 0x45, 0x2f, 0xbd, 0x68, 0xef, 0xb2, 0x5b, 0x88, 0x49, 0x6f,
	0x70, 0xd6, 0x6c, 0xb3, 0x90, 0xc2, 0x17, 0x5e, 0xb8, 0x33, 0x1d, 0x81, 0x96, 0xe2, 0xab, 0x23,
	0x98, 0xfb, 0x04, 0x83, 0xe5, 0x08, 0x48, 0x1c, 0x09, 0x16, 0x3e, 0xc1, 0xd8, 0x65, 0x77, 0x10,
	0x93, 0x36, 0xb6, 0xb4, 0xad, 0xc9, 0x96, 0x79, 0xf8, 0x3f, 0x2e, 0x85, 0x7b, 0xdc, 0x13, 0x1f,
	0x77, 0x64, 0xf2, 0x67, 0x2c, 0x6c, 0x68, 0x25, 0x85, 0x85, 0x6d, 0x2c, 0xc2, 0xcc, 0xf2, 0xa0,
	0x48, 0x9d, 0x7c, 0xdb, 0x37, 0x62, 0x87, 0xed, 0x38, 0x19, 0x43, 0x28, 0x94, 0xc5, 0xeb, 0x9d,
	0x48, 0x60, 0xae, 0xca, 0x5a, 0xe2, 0x85, 0x41, 0x11, 0xf1, 0x97, 0x69, 0x9d, 0xec, 0x0c, 0x56,
	0x46, 0x7e, 0xb6, 0x52, 0x09, 0xd9, 0xef, 0xc2, 0xbc, 0xa9, 0xbe, 0x65, 0xbf, 0x0a, 0x7d, 0xb1,
	0x95, 0x62, 0x67, 0xda, 0x9a, 0xda, 0x4c, 0xdc, 0x5b, 0x78, 0x9b, 0xb6, 0xb4, 0x90, 0xde, 0xc2,
	0x7d, 0x58, 0x0a, 0x0a, 0x7e, 0x3d, 0xa9, 0x7f, 0x32, 0xec, 0xbe, 0x38, 0xe1, 0x57, 0xa3, 0xce,
	0x07, 0x32, 0x67, 0x45, 0xfc, 0x71, 0x5a, 0xf3, 0x1f, 0x64, 0xa7, 0xb0, 0xec, 0x5b, 0x25, 0x36,
	0x9e, 0x4e, 0xda, 0xfb, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x28, 0x13, 0xdd, 0x7d, 0x02, 0x00,
	0x00,
}
